branches:
  only:
  - master

language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      install:
        - sudo apt-get install -y python3
      script:
        - travis_wait 50 docker build . -t felicia -f docker/Dockerfile.ubuntu
        - python3 scripts/docker_exec.py bazel build //felicia/...
        - python3 scripts/docker_exec.py bazel test --test_tag_filters -benchmark //felicia/...
        - python3 scripts/docker_exec.py bazel build -c dbg //felicia/...
        - python3 scripts/docker_exec.py bazel build -c dbg --test_tag_filters -benchmark //felicia/...
    - os: osx
      osx_image: xcode10.2
      sudo: required
      compiler: clang
      env:
        - PYTHON_BIN_PATH=/usr/local/bin/python3
      before_install:
        - sudo xcodebuild -license accept
      install:
        - ./installers/install_bazel.sh
      script:
        - bazel build --cpu darwin_x86_64 //felicia/...
        - bazel test --cpu darwin_x86_64 --test_tag_filters -benchmark //felicia/...
        - bazel build -c dbg --cpu darwin_x86_64 //felicia/...
        - bazel test -c dbg --cpu darwin_x86_64 --test_tag_filters -benchmark //felicia/...
notifications:
    email:
        on_success: always
        on_failure: always