branches:
  only:
  - master

language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      install:
        - sudo apt-get install -y python3
      script:
        - docker build . -t felicia -f docker/Dockerfile.ubuntu
        - python3 scripts/docker_exec.py bazel build --config linux //felicia/...
        - python3 scripts/docker_exec.py bazel test --config linux --test_tag_filters -benchmark //felicia/...
        - python3 scripts/docker_exec.py bazel clean
        - python3 scripts/docker_exec.py bazel build -c opt --config linux //felicia/...
        - python3 scripts/docker_exec.py bazel build -c opt --config linux --test_tag_filters -benchmark //felicia/...
    - os: osx
      osx_image: xcode10
      sudo: required
      compiler: clang
      before_install:
        - sudo xcodebuild -license accept
        # TODO(chokobole): When doing just "softwareupdate --install" with label,
        # Command Line Tools (macOS High Sierra version 10.13) for Xcode,
        # says Command Line Tools (macOS High Sierra version 10.13) for Xcode: No such update
        # so did workaround with -r option.
        - travis_wait 50 softwareupdate --install -r
      install:
        - ./installers/install_bazel.sh
      script:
        - bazel build --config darwin //felicia/...
        - bazel test --config darwin --test_tag_filters -benchmark //felicia/...
        - bazel clean
        - bazel build -c opt --config darwin //felicia/...
        - bazel test -c opt --config darwin --test_tag_filters -benchmark //felicia/...
notifications:
    email:
        on_success: always
        on_failure: always