branches:
  only:
  - master

language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      install:
        - sudo apt-get install -y python3
      script:
        - travis_wait 50 docker build . -t felicia -f docker/Dockerfile.ubuntu
        - python3 scripts/docker_exec.py bazel build //felicia/...
        - python3 scripts/docker_exec.py bazel test --test_tag_filters -benchmark //felicia/...
        - python3 scripts/docker_exec.py bazel build -c dbg //felicia/...
        - python3 scripts/docker_exec.py bazel build -c dbg --test_tag_filters -benchmark //felicia/...
    - os: osx
      osx_image: xcode10.2
      sudo: required
      compiler: clang
      env:
        - PYTHON_BIN_PATH=/usr/local/bin/python3
      install:
        - ./installers/install_bazel.sh
        - ./installers/install_nodejs.sh
        - ./installers/install_nodejs_deps.sh
        - ./installers/install_python_deps.sh
      script:
        - bazel build --cpu darwin_x86_64 //felicia/...
        - bazel test --cpu darwin_x86_64 --test_tag_filters -benchmark //felicia/...
        - bazel build -c dbg --cpu darwin_x86_64 //felicia/...
        - bazel test -c dbg --cpu darwin_x86_64 --test_tag_filters -benchmark //felicia/...
    - os: windows
      env:
        - USE_CLANG_CL=1
        - PYTHON_BIN_PATH=/c/Python3/python.exe
        - PATH="$PATH:/c/Python3:/c/Python3/Scripts:/c/Program Files/nodejs:/c/Users/travis/AppData/Roaming/npm"
      install:
        - choco install python3 --params "/InstallDir:C:\Python3"
        - ./installers/install_python_deps.sh
        - choco install bazel --version 0.20.0
        - choco install nodejs.install --version 10.15.3
        - ./installers/install_nodejs_deps.sh
      before_script:
      script:
        - bazel build //felicia/...
        - bazel test --test_tag_filters -benchmark //felicia/...
        - bazel build -c dbg //felicia/...
        - bazel test -c dbg --test_tag_filters -benchmark //felicia/...

notifications:
    email:
        on_success: always
        on_failure: always